//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibraryApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Abbreviations xmlns=&quot;http://tempuri.org/States.xsd&quot;&gt;
        ///&lt;State&gt;
        ///&lt;Name&gt;ALABAMA&lt;/Name&gt;
        ///&lt;Abbreviation&gt;AL&lt;/Abbreviation&gt;
        ///&lt;/State&gt;
        ///&lt;State&gt;
        ///&lt;Name&gt;ALASKA&lt;/Name&gt;
        ///&lt;Abbreviation&gt;AK&lt;/Abbreviation&gt;
        ///&lt;/State&gt;
        ///&lt;State&gt;
        ///&lt;Name&gt;AMERICAN SAMOA&lt;/Name&gt;
        ///&lt;Abbreviation&gt;AS&lt;/Abbreviation&gt;
        ///&lt;/State&gt;
        ///&lt;State&gt;
        ///&lt;Name&gt;ARIZONA&lt;/Name&gt;
        ///&lt;Abbreviation&gt;AZ&lt;/Abbreviation&gt;
        ///&lt;/State&gt;
        ///&lt;State&gt;
        ///&lt;Name&gt;ARKANSAS&lt;/Name&gt;
        ///&lt;Abbreviation&gt;AR&lt;/Abbreviation&gt;
        ///&lt;/State&gt;
        ///&lt;State&gt;
        ///&lt;Name&gt;CALIFORNIA&lt;/Name&gt;
        ///&lt;Abbr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string States {
            get {
                return ResourceManager.GetString("States", resourceCulture);
            }
        }
    }
}
